### ISSUE TITLE
Application.start() documentation

### ISSUE THREAD

**Issue by iquiw** [astoilkov/jsblocks-docs#7]
`Application.start()` seems not documented.
(I just found it from [your CodePen](http://codepen.io/astoilkov/pen/kIfLe).)

When I tried jsblock with [material-design-lite](https://github.com/google/material-design-lite), `Application.start()` is necessary to make material-design-lite work.

**Comment by Kanaye** [comment]
The codepen you linked uses an very, very old version. It even has no version number (no version property).
`Application.start()` will be called from blocks when creating the application / dom-ready.
You sholdn't have to call `Application.start()` yourself.

Are you sure you're using an up-to-date version of jsblocks?

**Comment by iquiw** [comment]
> Are you sure you're using an up-to-date version of jsblocks?

Yes, here's [the pen](http://codepen.io/iquiw/pen/MaBvZM/), using v0.3.4.

It won't work without `App.start()`. Maybe there is other way to work though.

**Comment by Kanaye** [comment]
Okay the issue with MDL is that MDL does evaluate the dom once at page load.
Without calling `App.start()` blocks modifys the dom after MDL did it's job, so MDL does not know the relation between the 'tabs' and the 'panels'.
When calling `App.start()` blocks registers a `readystatechange` handler before MDL does (blocks normaly does this async, so MDL would register before blocks) and gets called before MDL.

So far, so good/bad/whatever.

Now the real problem:
If you want e.g. add a `User` to your collection `users` later:

``` javascript
setTimeout(function() {
  App.UserProfile.users.add(User({
    firstName: 'Homer',
    lastName: 'Simpson'
  }));
}, 100);
```

blocks would add the corresponding HTML to the dom, but MDL will not reevaluate the dom.
So it won't work.

I don't think MDL is the best choice for frameworks like jsblocks as it's not designed to work well with MV-ish framworks.
Even angular needs [a plugin](https://github.com/jadjoubran/angular-material-design-lite) with special directives to work with it.
You (or someone else) _could_ write a similar plugin for blocks if needed.

Regarding the missing docs for `Application.start()`:
We can add it but as it's not needed in most cases and hooks would be the better choice in those cases (e.g. Views `options.ready`).
I don't think it's necessary to add it.

What do you think?
/cc @astoilkov

**Comment by astoilkov** [comment]
This is quite complete answer. I can confirm what you have find. I have previously seen such scenarios when there is another framework that kicks in and do DOM work when the document.body is ready. I have seen workarounds with calling `Application.start()` and subscribing to `View.ready` callback. Both of these can help but I can't say if it will work in all scenarios. More specifically in cases when the other framework could later update the DOM which probably will cause issues.

In general I haven't seen problems with workarounding these scenarios but @iquiw should be extra careful if the other framework makes additional DOM changes after the document have loaded.

**Comment by iquiw** [comment]
@Kanaye @astoilkov Thank you very much for the detailed answer!

As for MDL, it has [componentHandler](https://github.com/google/material-design-lite/blob/v1.0.6/src/mdlComponentHandler.js#L29) to upgrades elements manually, which can be used.
I have tried it, but it still needs `Application.start()`. I will check it again with `View.ready`.
