### ISSUE TITLE
A small typo in 'Why use jsblocks?' page

### ISSUE THREAD

**Issue by gamtiq** [astoilkov/jsblocks-docs#9]
There is a small typo in [Why use jsblocks?](https://github.com/astoilkov/jsblocks-docs/blob/master/introduction/why-jsblocks.md), [Forward thinking](https://github.com/astoilkov/jsblocks-docs/blob/master/introduction/why-jsblocks.md#forward-thinking) section :

> _Platform. not_ just a framework

**Comment by astoilkov** [comment]
I have fixed it - https://github.com/astoilkov/jsblocks-docs/commit/085e2dd9a4c3da1116f2894405283eb11ecec955.

Thanks for reporting.
